{% set name = "opencamlib" %}
{% set version = "2023.01.11" %}
{% set sha256 = "07fd9b61c39c4d600e441d67edbafc1015e9e3fabd88b561a647f98fedf31d41" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/aewallin/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - patches/boost-shared.patch
        - patches/compile_definitions.patch
        - patches/version_string.patch

build:
    number: 3
    skip: true  # [py<36]

requirements:
    build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja
        - cmake
        - make
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
    host:
        - python
        - pip
        - scikit-build-core
        - libboost-devel
        - libboost-python-devel
    run:
        - python
        - libboost-python

test:
  imports:
    - opencamlib
  source_files:
    - examples/python/test.py
    - stl/**
about:
    home: http://www.anderswallin.net/CAM/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: COPYING
    summary: OpenCAMLib (ocl)
    description: OpenCAMLib (ocl) is a C++ library for creating toolpaths for CNC-machines
                 such as mills and lathes.
    doc_url: http://www.anderswallin.net/CAM/
    dev_url: https://github.com/aewallin/opencamlib

extra:
  recipe-maintainers:
    - adrianinsaval
    - looooo
    - vespakoen
